// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swbpgrcwrcmepxxokrsz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3YnBncmN3cmNtZXB4eG9rcnN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MzU1MDAsImV4cCI6MjA2MjIxMTUwMH0.eyBj7d5oIYkDd0t_o_FYG8H-2bh0yLsPCzC41VvpqdE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);